"""Network engine: wire a device into the analysis network, from anywhere.

Provides the device-side plumbing that makes dynamic analysis work regardless of
where the target device physically sits:

* **Local network**: point a device's global HTTP proxy (or ``adb reverse``) at
  the mitmproxy host and install the mitmproxy CA certificate.
* **Anywhere**: bring up mitmproxy's WireGuard mode and emit the client config
  (plus an ASCII QR when ``qrcode`` is available) so a physical device on any
  network tunnels its traffic back to the analysis host.

Host-IP discovery is cross-platform (``socket`` + ``psutil``); certificate and
proxy wiring use ``adb``.
"""
from __future__ import annotations

import socket
from pathlib import Path
from typing import Any

from .. import device as dev
from ..config import Config
from ..exceptions import EngineError
from ..platform_utils import which
from ..registry import register
from .base import Engine, action
from .proxy import ProxyEngine

try:
    import psutil
except Exception:  # pragma: no cover
    psutil = None  # type: ignore[assignment]


@register
class NetworkEngine(Engine):
    """Set up the dynamic-analysis network for local or remote devices."""

    name = "network"
    summary = "Wire a device (local or anywhere) into the mitmproxy analysis network."

    def __init__(self, config: Config) -> None:
        super().__init__(config)
        self.proxy = ProxyEngine(config)

    def preflight(self) -> dict[str, Any]:
        return {
            "engine": self.name,
            "ready": which("adb") is not None,
            "details": {
                "adb": which("adb"),
                "primary_ip": self._primary_ip(),
                "ca_cert": str(self._ca_cert_path()),
            },
        }

    # -- host IP discovery ------------------------------------------------

    def _primary_ip(self) -> str | None:
        """Best-effort discovery of the host's outward-facing IPv4 address."""
        try:
            s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
            try:
                s.connect(("8.8.8.8", 80))
                return s.getsockname()[0]
            finally:
                s.close()
        except OSError:
            return None

    @action("List host IP addresses a device could target (per interface).")
    def host_ips(self) -> dict[str, Any]:
        interfaces: dict[str, list[str]] = {}
        if psutil is not None:
            for name, addrs in psutil.net_if_addrs().items():
                ips = [a.address for a in addrs if a.family == socket.AF_INET]
                if ips:
                    interfaces[name] = ips
        return {"primary": self._primary_ip(), "interfaces": interfaces}

    # -- CA certificate ---------------------------------------------------

    def _ca_cert_path(self) -> Path:
        return Path.home() / ".mitmproxy" / "mitmproxy-ca-cert.pem"

    @action("Push the mitmproxy CA certificate to a device for user install.", mutating=True)
    def install_ca(self, serial: str | None = None) -> dict[str, Any]:
        """Push the mitmproxy CA cert to the device.

        The cert is generated by mitmproxy on first run. It is pushed to
        ``/sdcard/Download`` so it can be installed via Settings; on a rooted
        device the returned ``rooted_hint`` shows how to install it as a trusted
        system CA (required to intercept apps that ignore user CAs on Android 7+).
        """
        cert = self._ca_cert_path()
        if not cert.is_file():
            raise EngineError(
                "network",
                "mitmproxy CA cert not found. Start a capture once "
                "('proxy start-capture') so mitmproxy generates it.",
            )
        serial = dev.resolve_serial(serial)
        remote = "/sdcard/Download/mitmproxy-ca-cert.pem"
        dev.push(cert, remote, serial=serial)

        # Android system CAs are named <subject_hash>.0.
        rooted_hint = (
            "If the device is rooted: compute the hash with "
            "`openssl x509 -inform PEM -subject_hash_old -in mitmproxy-ca-cert.pem`, "
            "then `adb push` it to /system/etc/security/cacerts/<hash>.0 "
            "(remount /system rw) and reboot."
        )
        return {
            "device": serial,
            "pushed_to": remote,
            "install": "Settings > Security > Install a certificate > CA certificate",
            "rooted_hint": rooted_hint,
        }

    # -- local proxy wiring ----------------------------------------------

    @action("Point a device's global HTTP proxy at the mitmproxy host.", mutating=True)
    def set_device_proxy(
        self,
        host: str | None = None,
        port: int | None = None,
        serial: str | None = None,
    ) -> dict[str, Any]:
        """Set the device-wide HTTP proxy to ``host:port`` (defaults to this host)."""
        serial = dev.resolve_serial(serial)
        host = host or self._primary_ip()
        if not host:
            raise EngineError("network", "Could not determine host IP; pass host=...")
        port = port or self.config.proxy.listen_port
        dev.set_global_http_proxy(f"{host}:{port}", serial=serial)
        return {"device": serial, "proxy": f"{host}:{port}"}

    @action("Clear a device's global HTTP proxy.", mutating=True)
    def clear_device_proxy(self, serial: str | None = None) -> dict[str, Any]:
        serial = dev.resolve_serial(serial)
        dev.clear_global_http_proxy(serial=serial)
        return {"device": serial, "proxy": "cleared"}

    @action(
        "Set up a full LOCAL interception network: proxy + adb wiring hints.",
        mutating=True,
    )
    def setup_local(
        self,
        serial: str | None = None,
        use_reverse: bool = False,
    ) -> dict[str, Any]:
        """One-shot local setup for a device on the same network (or via USB).

        Args:
            serial: Target device.
            use_reverse: If True, use ``adb reverse`` so the device reaches the
                proxy over USB via ``127.0.0.1`` (no shared Wi-Fi needed).
        """
        serial = dev.resolve_serial(serial)
        port = self.config.proxy.listen_port
        steps: list[str] = []

        if use_reverse:
            dev.reverse(port, port, serial=serial)
            dev.set_global_http_proxy(f"127.0.0.1:{port}", serial=serial)
            steps.append(f"adb reverse tcp:{port} tcp:{port}")
            steps.append(f"device http_proxy -> 127.0.0.1:{port}")
            target = f"127.0.0.1:{port}"
        else:
            host = self._primary_ip()
            if not host:
                raise EngineError("network", "Could not determine host IP.")
            dev.set_global_http_proxy(f"{host}:{port}", serial=serial)
            steps.append(f"device http_proxy -> {host}:{port}")
            target = f"{host}:{port}"

        return {
            "device": serial,
            "proxy_target": target,
            "steps": steps,
            "next": "Run 'network install-ca' and 'proxy start-capture' if not already.",
        }

    # -- anywhere (WireGuard) --------------------------------------------

    @action(
        "Bring up a WireGuard interception tunnel so a device ANYWHERE can connect.",
        background=True,
        mutating=True,
    )
    def setup_anywhere(self, show_qr: bool = True) -> dict[str, Any]:
        """Start mitmproxy in WireGuard mode and return the device client config.

        The device imports the returned WireGuard config (scan the QR, or paste
        the config into the WireGuard app) to route all its traffic through this
        host's mitmproxy, so no shared network is required. Ensure the host's
        WireGuard UDP port is reachable (port-forward / VPS) for true "anywhere".
        """
        started = self.proxy.start_capture(mode="wireguard")
        conf = self._wireguard_conf()
        result: dict[str, Any] = {
            "proxy": started,
            "wireguard_conf_path": str(conf["path"]) if conf else None,
            "wireguard_conf": conf["text"] if conf else None,
            "note": (
                "Import this config into the WireGuard app on the target device. "
                "For a device on a remote network, forward the WireGuard UDP port "
                f"({self.config.proxy.wireguard_port}) to this host."
            ),
        }
        if show_qr and conf:
            result["qr"] = self._ascii_qr(conf["text"])
        return result

    def _wireguard_conf(self) -> dict[str, Any] | None:
        # mitmproxy writes the client config here on first WireGuard run.
        candidates = [
            Path.home() / ".mitmproxy" / "wireguard.conf",
            self.config.logs_dir / "mitmproxy.log",
        ]
        conf_file = candidates[0]
        if conf_file.is_file():
            return {"path": conf_file, "text": conf_file.read_text()}
        return None

    def _ascii_qr(self, text: str) -> str | None:
        try:
            import qrcode  # optional dependency

            qr = qrcode.QRCode(border=1)
            qr.add_data(text)
            qr.make(fit=True)
            from io import StringIO

            buf = StringIO()
            qr.print_ascii(out=buf)
            return buf.getvalue()
        except Exception:
            return None
